### ISSUE TITLE
installation issue on python3.10

### ISSUE THREAD

**Issue by kargaranamir** [tamuhey/textspan#7]
Hi, 

Your package installs fine on Python3.9 and lower, but when it comes to Python3.10, it fails. Here is a screenshot. Thanks.

<img width="834" alt="Screen Shot 2022-12-28 at 1 29 28 PM" src="https://user-images.githubusercontent.com/26163093/209812642-67a27896-2067-4a8b-8c27-ce6cd1c47530.png">

**Comment by tamuhey** [comment]
Hi @kargaranamir , thanks for reporting the issue. I'm working on it in https://github.com/tamuhey/textspan/pull/8

**Comment by tamuhey** [comment]
Released version 0.5.7, which should solve this issue.

**Comment by kargaranamir** [comment]
> Released version 0.5.7, which should solve this issue.

Confirmed, it works well.
